{
 "title": "Smartmeter Application Metrics",
 "tags": [ "smartmeter" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "smartmeter_app_uptime_seconds", "legendFormat": "Uptime" }
   ]
  },
  {
   "title": "Serial Restarts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smartmeter_app_serial_restarts_total",
     "legendFormat": "Restarts"
    }
   ]
  },
  {
   "title": "MQTT Write Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smartmeter_app_mqtt_write_success",
     "legendFormat": "Status"
    }
   ]
  },
  {
   "title": "InfluxDB Write Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smartmeter_app_influxdb_write_success",
     "legendFormat": "Status"
    }
   ]
  },
  {
   "title": "Failed Write Operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "smartmeter_app_mqtt_write_failures_total",
     "legendFormat": "MQTT Failures"
    },
    {
     "expr": "smartmeter_app_influxdb_write_failures_total",
     "legendFormat": "InfluxDB Failures"
    }
   ]
  },
  {
   "title": "Success Write Operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "smartmeter_app_mqtt_write_successes_total",
     "legendFormat": "MQTT Successes"
    },
    {
     "expr": "smartmeter_app_influxdb_write_successes_total",
     "legendFormat": "InfluxDB Successes"
    }
   ]
  }
 ]
}